# Learn more → https://github.com/TryGhost/action-deploy-theme#getting-started
name: Deploy Theme
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs: 
  deploy:
    #  checks for runners with label runner-k3s, if active use it, failover to ubuntu:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          fetch-depth: 1
          persist-credentials: false
      
      - name: Deploy Ghost Theme to website
        uses: sredevopsorg/action-deploy-theme@main
        continue-on-error: false
        with:
          api-url: ${{ secrets.SREDEVOPS_API_URL }}
          api-key: ${{ secrets.SREDEVOPS_ADMIN_API_KEY }}
